// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AddProductReq struct {
	Name        string            `json:"name"`               // 商品名称（必填）
	Description string            `json:"description"`        // 商品详情（富文本或 Markdown）
	CategoryId  uint              `json:"categoryId"`         // 类目 ID（如“女装 > 连衣裙”）
	Brand       string            `json:"brand"`              // 品牌（可选）
	Price       float64           `json:"price"`              // 原价（单位：元，建议用分存储，但 API 用元更友好）
	SalePrice   *float64          `json:"salePrice,optional"` // 促销价（可选，若为空则按原价卖）
	Attributes  map[string]string `json:"attributes"`         // 自定义属性，如 {"材质": "纯棉", "适用季节": "夏季"}
	SKUs        []ProductSKU      `json:"skus"`               // SKU 列表（支持多规格）
}

type AddProductResp struct {
	Id uint `json:"id"`
}

type GetProductReq struct {
	Id uint `path:"id"`
}

type GetProductResp struct {
	Id          uint              `json:"id"`
	Name        string            `json:"name"`                // 商品名称（必填）
	Description string            `json:"description"`         // 商品详情（富文本或 Markdown）
	CategoryId  uint              `json:"categoryId"`          // 类目 ID（如“女装 > 连衣裙”）
	Brand       string            `json:"brand"`               // 品牌（可选）
	Price       float64           `json:"price"`               // 原价（单位：元，建议用分存储，但 API 用元更友好）
	SalePrice   *float64          `json:"salePrice,omitempty"` // 促销价（可选，若为空则按原价卖）
	Attributes  map[string]string `json:"attributes"`          // 自定义属性，如 {"材质": "纯棉", "适用季节": "夏季"}
	SKUs        []ProductSKU      `json:"skus"`                // SKU 列表（支持多规格）
	Status      string            `json:"status"`              // 商品状态：active, inactive, pending, deleted
	TotalStock  uint              `json:"totalStock"`          // 所有 SKU 库存之和（便于前端展示）
}

type ProductSKU struct {
	Specs   map[string]string `json:"specs"`   // 规格组合，如 {"颜色": "红色", "尺寸": "L"}
	Price   float64           `json:"price"`   // 该 SKU 价格（可覆盖商品级价格）
	Stock   uint              `json:"stock"`   // 该 SKU 库存
	SKUCode string            `json:"skuCode"` // 商家自定义 SKU 编码（可选）
}
