services:
  hello-middleware:
    # build:
    #   context: .
    #   dockerfile: dockerfiles/Dockerfile
    image: hello-middleware:latest  # 构建后镜像的名称和标签
    restart: unless-stopped # 重启策略
    networks:
      - default
      - pulsar-cluster # pulsar 集群访问
    environment:
      # -- pulsar
      PULSAR_BROKER_URL: pulsar://pulsar-cluster-broker:6650
      PULSAR_DEFAULT_TOPIC: persistent://public/default/test-topic
    volumes:
      - .:/root/hello-middleware
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
    working_dir: /root/hello-middleware
    # sleep infinity 用于保持容器运行，否则 vscode 无法进入容器，建议写在 .devcontainer/docker-compose.yml 文件中
    command: ["sleep", 'infinity']


networks:
  default:
    name: hello-middleware-network
  