services:
  hello-middleware:
    image: hello-middleware:1.0.2  # 构建后镜像的名称和标签
    # build:  # recommended to use `scripts/docker-pre-build.sh` to build the image
    #   context: .
    #   dockerfile: dockerfiles/Dockerfile
    
    restart: unless-stopped # 重启策略
    networks:
      - default
    environment:
      # -- pulsar
      PULSAR_BROKER_URL: pulsar://pulsar-cluster-broker:6650
      PULSAR_DEFAULT_TOPIC: persistent://public/default/test-topic
    volumes:
      - .:/root/app
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
    working_dir: /root/app
    command: ["sleep", 'infinity']


networks:
  default:
    name: hello-middleware-network
  