services:
  hello-middleware:
    image: hello-middleware:1.0.2  # 构建后镜像的名称和标签
    # build:  # recommended to use `scripts/docker-pre-build.sh` to build the image
    #   context: .
    #   dockerfile: dockerfiles/Dockerfile
    
    restart: unless-stopped # 重启策略
    networks:
      - default
    environment:
      # -- mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_secret_password}
      - MYSQL_DATABASE=default_db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=my_secret_password
      # --mongo
      - MONGO_HOST=mongodb-standalone   # mongoDB 服务的主机名
      - MONGO_INITDB_ROOT_USERNAME=root # 初始化数据库的根用户名
      - MONGO_INITDB_ROOT_PASSWORD=root # 初始化数据库的根密码
      # - MONGO_INITDB_DATABASE=defaul_db
    volumes:
      - .:/root/app
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
    working_dir: /root/app
    command: ["sleep", 'infinity']


networks:
  default:
    name: hello-middleware-network
  