services:
  mongodb-standalone:
    image: mongo:8.0 # https://hub.docker.com/_/mongo
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=root  # 初始化数据库的根用户名
      - MONGO_INITDB_ROOT_PASSWORD=root  # 初始化数据库的根密码
      - MONGO_INITDB_DATABASE=defaul_db
      # - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      # - MONGODB_SYSTEM_LOG_VERBOSITY=3
    ports:
      - "27017:27017"
    volumes:
      - mongodb_standalone_data:/data/db 
    healthcheck:
      test: mongosh --eval "db.runCommand('ping').ok" || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:  # 资源限制
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M

volumes:
  mongodb_standalone_data:
