services:
  # Mongo Cluster
  mongo-cluster:
    image: mongo:8 # https://hub.docker.com/_/mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # 数据持久化
      
volumes:
  mongo_data: