# https://docs.docker.com/reference/compose-file/services/
services:
  # ports:
  #   - "6379" # Standard Redis command port.
  #   - "16379" # Cluster bus port (cluster-node-timeout uses this).
  redis-init-job:
    image: redis:8
    container_name: redis-init-job
    networks:
      - redis-cluster-net
    depends_on:
      - redis-leader-0
      - redis-leader-1
      - redis-leader-2
      - redis-follower-0
      - redis-follower-1
      - redis-follower-2
    volumes:
      # 挂载初始化脚本
      - ./init.d/redis/init-job.sh:/etc/init.d/init-job.sh:ro
    entrypoint: ["/bin/bash", "/etc/init.d/init-job.sh"]
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-leader-0", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 节点 0
  redis-leader-0:
    image: redis:8
    container_name: redis-leader-0
    networks:
      - redis-cluster-net
    command: |
      redis-server  --cluster-enabled yes --cluster-announce-ip redis-leader-0 --appendonly yes --cluster-node-timeout 5000 --cluster-config-file nodes.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
  redis-follower-0:
    image: redis:8
    container_name: redis-follower-0
    networks:
      - redis-cluster-net
    command: |
      redis-server  --cluster-enabled yes --cluster-announce-ip redis-follower-0 --appendonly yes --cluster-config-file nodes.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
    

  
  # 节点 1
  redis-leader-1:
    image: redis:8
    container_name: redis-leader-1
    networks:
      - redis-cluster-net
    command: |
      redis-server  --cluster-enabled yes --cluster-announce-ip redis-leader-1 --appendonly yes --cluster-node-timeout 5000 --cluster-config-file nodes.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
  redis-follower-1:
    image: redis:8
    container_name: redis-follower-1
    networks:
      - redis-cluster-net
    command: |
      redis-server  --cluster-enabled yes --cluster-announce-ip redis-follower-1 --appendonly yes --cluster-config-file nodes.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
    
  # 节点 2
  redis-leader-2:
    image: redis:8
    container_name: redis-leader-2
    networks:
      - redis-cluster-net
    command: |
      redis-server  --cluster-enabled yes --cluster-announce-ip redis-leader-2 --appendonly yes --cluster-node-timeout 5000 --cluster-config-file nodes.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
  redis-follower-2:
    image: redis:8
    container_name: redis-follower-2
    networks:
      - redis-cluster-net
    command: |
      redis-server  --cluster-enabled yes --cluster-announce-ip redis-follower-2 --appendonly yes --cluster-config-file nodes.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
    
  

networks:
  redis-cluster-net:
    name: redis-cluster-net
    driver: bridge
    # docker pull docker-0.unsee.tech/library/redis:8