services:
  # Elasticsearch
  elasticsearch-server:
    image: bitnami/elasticsearch:8.17.1 # https://hub.docker.com/r/bitnami/elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  elasticsearch_data: