// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	product "github.com/henryzhuhr/hello-middleware/app/redis-product-cache/internal/handler/product"
	"github.com/henryzhuhr/hello-middleware/app/redis-product-cache/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product",
				Handler: product.AddProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/:id",
				Handler: product.GetProductHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
